Update Cromha Expansion.yaml
endless-sky/endless-sky-plugins pull request #1013
Opened 2023-08-03 21:23 UTC by OcelotWalrus

Use Continuous Build instead of releases.

I made so it still update the version name.

2023-08-03 21:37 UTC, OcelotWalrus commented
Since my Continuous Build refresh at every push, there is no difference with the commit tracking stuff.

2023-08-04 06:49 UTC, MCOfficer commented
I would still prefer a commit-based manifest. The point of PRs is that changes can be reviewed before they're merged.

2023-08-04 07:13 UTC, OcelotWalrus commented
Sure! I made it commit based.

I just have a problem, how do I do for the download url? Do I make it the continuous url?

2023-08-04 07:14 UTC, MCOfficer commented on manifests/Cromha Expansion.yaml
> +
```suggestion
```

2023-08-04 07:57 UTC, OcelotWalrus commented
@CMOfficer could you merge it right now? Because I want to commit to my repository without having to update my manifest file.

2023-08-04 15:47 UTC, MCOfficer requested changes

2023-08-04 15:47 UTC, MCOfficer commented on manifests/Cromha Expansion.yaml
> +url: https://github.com/OcelotWalrus/Cromha-Expansion-plugin/releases/download/9.9.9-continuous/Cromha-Expansion-plugin.zip
```suggestion
url: https://github.com/OcelotWalrus/Cromha-Expansion-plugin/archive/92f5020b0cbfb7f3dbfe80900ac8ae9c6eaaf482.zip
```

2023-08-04 15:47 UTC, MCOfficer commented on manifests/Cromha Expansion.yaml
> +  url: https://github.com/OcelotWalrus/Cromha-Expansion-plugin/releases/download/9.9.9-continuous/Cromha-Expansion-plugin.zip
```suggestion
  url: https://github.com/OcelotWalrus/Cromha-Expansion-plugin/archive/$version.zip
```

2023-08-04 16:16 UTC, lumbar527 commented
> Will let this sit for a few hours so others have the chance to chime in.

Does that mean wait for other peoples opinion? If so, then I think it makes a little more sense to have the plugin page/ESLauncher display the continuous, rather than release, because it is in beta anyway and new things are added quickly.

2023-08-04 16:21 UTC, lumbar527 commented
I might be misinterpreting some, but I think it should be done by commit, not regularly updated release.

2023-08-04 16:48 UTC, merged